# Generated by Django 4.2.4 on 2023-08-02 08:03

from django.db import migrations, models
import faebikes_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faebikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_no', models.CharField(max_length=50)),
                ('bike_name', models.CharField(max_length=50)),
                ('bike_model', models.CharField(max_length=50)),
                ('bike_images', models.ImageField(blank=True, null=True, upload_to=faebikes_app.models.upload_to)),
            ],
        ),
    ]
